name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update gist
        uses: shiwei-Ren/shiwei-Ren@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c90b910953a006aa0110222d46d1f1c0
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
