name: Update gist with WakaTime stats
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: shiwei-Ren/shiwei-Ren@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
